ma_sv = input("Nhập mã sinh viên: ")
ho_ten = input("Nhập họ tên: ")
que_quan = input("Nhập quê quán: ")
nam_sinh = int(input("Nhập năm sinh: "))
diem_tb = float(input("Nhập điểm trung bình: "))
print("Mã sinh viên là: ")
print("Họ và tên: ")
print("Quê quán: ")
print("Năm sinh: ")
print("Điểm trung bình qua các năm học: ")