ban_kinh = int(input("Nhập bán kính của khối trụ: "))
chieu_cao = int(input("Nhập chiều cao của khối trụ: "))
dien_tich_xung_quanh = round(2 * 3.14 * ban_kinh * chieu_cao, 2)
dien_tich_toan_phan = round((2 * 3.14 * ban_kinh * chieu_cao) + (2 * 3.14 * ban_kinh**2), 2)
the_tich = round(3.14* ban_kinh**2 * chieu_cao, 2)
print(f"Diện tích xung quanh: {dien_tich_xung_quanh}")
print(f"Diện tích toàn phần: {dien_tich_toan_phan}")
print(f"Thể tích: {the_tich}") 