x1=float(input('nhap x1: '))
x2=float(input('nhap x2: '))
y1=float(input('nhap y1: '))
y2=float(input('nhap y2: '))
z1=float(input('nhap z1: '))
z2=float(input('nhap z2: '))
s1,s2=round((x1+y1+y1)/3,2),round((x2+y2+z2)/3,2)
print(f'toa do cua trong tam la: x={s1},y={s2}')