x= float(input('nhap x: '))
y=float(input('nhap y: '))
z=float(input('nhap z: '))
print(f'toa do doi xung qua oxy:x={x},y={y},z={-z}')
print(f'toa do doi xung qua oxz:x={x},y={-y},z={z}')
print(f'toa do doi xung qua oyz:x={-x},y={y},z={-z}')