x=float(input("Nhap x: "))
y=float(input("Nhap y: "))
z=float(input("Nhap z: "))
diem_doi_xung_Oxy=(x,y,-z*2)
diem_doi_xung_Oxz=(x,-y*2,z)
diem_doi_xung_Oyz=(-x*2,y,z)
print(f"Toa do cua diem doi xung qua mat phang Oxy la: {diem_doi_xung_Oxy}")
print(f"Toa do cua diem doi xung qua mat phang Oxz la: {diem_doi_xung_Oxz}")
print(f"Toa do cua diem doi xung qua mat phang Oyz la: {diem_doi_xung_Oyz}") 