x1 = int(input("nhập vào x1:"))
x2 = int(input("nhập vào x2:"))
x3 = int(input("nhập vào x3:"))
y1 = int(input("nhập vào y1:"))
y2 = int(input("nhập vào y2:"))
y3 = int(input("nhập vào y3:"))
xG = round(x1+x2+x3/3, 2)
yG = round(y1+y2+y3/3, 2)
print(f"tọa độ của x = {xG}, tọa độ của y = {yG}")