x = float(input("Nhập vào tọa độ x: "))
y = float(input("Nhập vào tọa độ y: "))
z = float(input("Nhập vào tọa độ z: "))
doi_xung_Oxy = (x, y, -z)
doi_xung_Oxz = (x, -y, z)
doi_xung_Oyz = (-x, y, z)
print("toa do doi xung qua mat Oxy: ",doi_xung_Oxy)
print("toa do doi xung qua mat Oxz: ",doi_xung_Oxz)
print("toa do doi xung qua mat Oyz: ",doi_xung_Oyz)