print("CHƯƠNG TRÌNH NHẬP THÔNG TIN CỦA SINH VIÊN")
ma_sv = int(input("Nhập mã sinh viên: "))
ho_ten = input("Nhập họ tên sinh viên: ")
que_quan = input("Nhập quê quán: ")
nam_sinh = int(input("Nhập năm sinh: "))
diem_trung_binh = float(input("Nhập điểm trung bình của sinh viên: "))
print(ma_sv)
print(ho_ten)
print(que_quan)
print(nam_sinh)
print(diem_trung_binh)