a1 = float(input("nhập tọa độ a1: "))
b1 = float(input("nhập tọa độ b1: "))
c1 = float(input("nhập tọa độ c1: "))
print(f"tọa độ đỉnh A{a1, b1, c1}")
a2 = float(input("nhập tọa độ a2: "))
b2 = float(input("nhập tọa độ b2: "))
c2 = float(input("nhập tọa độ c2: "))
print(f"tọa độ đỉnh B{a2, b2, c2}")
a3 = float(input("nhập tọa độ a3: "))
b3 = float(input("nhập tọa độ b3: "))
c3 = float(input("nhập tọa độ c3: "))
print(f"tọa độ đỉnh C{a3, b3, c3}")
print("tọa độ trọng tâm là:", "(",((a1+a2+a3)/3),",", ((b1+b2+b3)/3),",", ((c1+c2+c3)/3),")")
