xA = int(input("Nhập tọa độ x của điểm A: "))
yA = int(input("Nhập tọa độ y của điểm A: "))
zA = int(input("Nhập tọa độ z của điểm A: "))
diem_doi_xung_Oxy = (xA,yA,-zA)
diem_doi_xung_Oxz = (xA,-yA,zA)
diem_doi_xung_Oyz = (-xA,yA,zA)
print("Tọa độ điểm đối xứng A qua Oxy là: ",diem_doi_xung_Oxy)
print("Tọa độ điểm đối xứng A qua Oxz là: ",diem_doi_xung_Oxz)
print("Tọa độ điểm đối xứng A qua Oyz là: ",diem_doi_xung_Oyz)
