ma_sv = input("Nhap ma sinh vien: ")
ho_ten = input('Nhap ho va ten: ')
que_quan = input("Nhap que quan: ")
nam_sinh = int(input('Nhap nam sinh: '))
diem_tb = float(input("Nhap diem trung binh: "))
print("Thong tin cua sinh vien la")
print("Ma sinh vien: ", ma_sv)
print("Ho va ten: ", ho_ten)
print("Que quan: ", que_quan)
print("Nam sinh: ", nam_sinh)
print("Diem trung binh: ", diem_tb)