x = float(input("Nhập tọa độ x: "))
y = float(input("Nhập tọa độ y: "))
z = float(input("Nhập tọa độ z: "))
dx_Oxy = (x, y, -z)
dx_Oxz = (x, -y, z)
dx_Oyz = (-x, y, z)
print("dx của Oxy: ", dx_Oxy)
print("dx của Oxz: ", dx_Oxz)
print("dx của Oyz: ", dx_Oyz)